import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { requireWriter } from '@/lib/admin-auth'

// Avoid running this route at build time — it needs runtime env vars.
export const dynamic = 'force-dynamic'

function getSupabase() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) {
    throw new Error('Missing Supabase environment variables')
  }
  return createClient(url, key)
}

export async function POST(req: NextRequest) {
  try {
    const g = await requireWriter('businesses'); if (g.error) return g.error
    const supabase = getSupabase()
    const { name, email, cat, estado, municipio, plan } = await req.json()

    if (!name || !email) {
      return NextResponse.json({ error: 'name and email are required' }, { status: 400 })
    }

    // Insert invitation row — token is generated by DB default
    const { data: inv, error: dbErr } = await supabase
      .from('biz_invitations')
      .insert({ biz_name: name, email, cat, estado, municipio, plan: plan ?? 'Reva', invited_by: 'admin@reva.mx' })
      .select('token')
      .single()

    if (dbErr) {
      console.error('DB insert error:', dbErr)
      return NextResponse.json({ error: 'Could not create invitation' }, { status: 500 })
    }

    const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://reva-app-ten.vercel.app'
    const inviteUrl = `${appUrl}/biz/register?token=${inv.token}`

    // Invoke the Supabase Edge Function
    const { error: fnErr } = await supabase.functions.invoke('send-biz-invite', {
      body: { email, bizName: name, token: inv.token, inviteUrl, plan },
    })

    if (fnErr) {
      // supabase-js wraps a non-2xx function response in a FunctionsHttpError whose
      // `context` is the raw Response — read it so the real reason (e.g. Resend
      // sandbox restriction / unverified domain) actually shows up in the logs.
      let detail: unknown = fnErr.message
      const ctx = (fnErr as { context?: Response }).context
      if (ctx && typeof ctx.text === 'function') {
        try { detail = await ctx.clone().json() } catch { detail = await ctx.text() }
      }
      console.error('Edge function error (send-biz-invite):', detail)
      // Invitation row already created — log the error but don't fail the request
      return NextResponse.json({ ok: true, warning: 'Invitation saved but email delivery failed', detail })
    }

    return NextResponse.json({ ok: true })
  } catch (err) {
    console.error('invite-business error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
