import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

// Avoid running this route at build time — it needs runtime env vars.
export const dynamic = 'force-dynamic'

function getSupabase() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  if (!url || !key) {
    throw new Error('Missing Supabase environment variables')
  }
  return createClient(url, key)
}

export async function POST(req: NextRequest) {
  try {
    const supabase = getSupabase()
    const { name, email, cat, estado, municipio, plan } = await req.json()

    if (!name || !email) {
      return NextResponse.json({ error: 'name and email are required' }, { status: 400 })
    }

    // Insert invitation row — token is generated by DB default
    const { data: inv, error: dbErr } = await supabase
      .from('biz_invitations')
      .insert({ biz_name: name, email, cat, estado, municipio, plan: plan ?? 'Reva', invited_by: 'admin@reva.mx' })
      .select('token')
      .single()

    if (dbErr) {
      console.error('DB insert error:', dbErr)
      return NextResponse.json({ error: 'Could not create invitation' }, { status: 500 })
    }

    const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://reva.mx'
    const inviteUrl = `${appUrl}/biz/register?token=${inv.token}`

    // Invoke the Supabase Edge Function
    const { error: fnErr } = await supabase.functions.invoke('send-biz-invite', {
      body: { email, bizName: name, token: inv.token, inviteUrl, plan },
    })

    if (fnErr) {
      console.error('Edge function error:', fnErr)
      // Invitation row already created — log the error but don't fail the request
      return NextResponse.json({ ok: true, warning: 'Invitation saved but email delivery failed' })
    }

    return NextResponse.json({ ok: true })
  } catch (err) {
    console.error('invite-business error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
